version: '3'

services:

  ss-bookmarks:
    build: ./
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./ss-bookmarks.php:/var/www/html/index.php
    environment:
      - 'CONTAINER_TIMEZONE=Australia/Perth'
      - 'APACHE_SERVER_NAME=localhost'
      - 'PHP_DATE_TIMEZONE=Australia\/Perth'
      - 'PHP_ERROR_REPORTING=E_ALL'
      - 'PHP_DISPLAY_ERRORS=On'
      - 'PHP_VARIABLES_ORDER=EGPCS'
    cap_add:
      - SYS_TIME
      - SYS_NICE